### ISSUE TITLE
Should the language name be changed to something else?

### ISSUE THREAD

**Issue by 0x0f0f0f** [0x0f0f0f/gobba#15]
`minicaml` is no longer `mini` at ~2.1k lines of code, and while it still has a lot in common with OCaml, the syntax has diverged and the name `minicaml` may be misleading for newcomers. 
I thought about `gobba` (camel hump in Italian) name with a `.gob` extension for language files.
Let me know if you have any other ideas for a project name (or if you like the current name).

**Comment by tekknolagi** [comment]
I propose Dromedarius (from the scientific name for camel, "Camelus Dromedarius").

**Comment by Stupremee** [comment]
I think Dromedarius is too long but you can shorten it to drom

**Comment by kleinesfilmroellchen** [comment]
MALC: MALC Ain't Like Caml. Because recursive acronyms (see YAML or PHP)

**Comment by tekknolagi** [comment]
Well it looks like it's now called gobba :P

**Comment by 0x0f0f0f** [comment]
I've made a poll on various telegram groups and the 29% of 66 people chose gobba! The other 2 most popular were guanaco at 16% and dromedarious at 9%. Thank you for the ideas btw!
